[project]
name = "oa-ontology"
version = "0.1.0"
description = "OpenAccess Ontology Explorer - Extract and analyze the ontology of the Cadence OpenAccess API"
authors = [
    {name = "Robert Taylor", email = ""}
]
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
dependencies = [
    "networkx>=2.8.0",
    "pyyaml>=6.0",
    "tqdm>=4.64.0", 
    "beautifulsoup4>=4.11.0"
]

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
dev = [
    "black>=23.3.0",
    "pylint>=2.17.0",
    "pytest>=7.3.1",
]

[project.scripts]
oa-setup = "oa_ontology.setup:main"
oa-parse = "oa_ontology.parse_html:main"
oa-build = "oa_ontology.build_ontology:main"
oa-domain = "oa_ontology.extract_domain_ontology:main"
oa-export = "oa_ontology.export_to_neo4j:main"
oa-visualize = "oa_ontology.visualize_ontology:main"
oa-run-all = "oa_ontology.run_all:main"

[project.urls]
Homepage = "https://github.com/username/oa-ontology"
Documentation = "https://github.com/username/oa-ontology#readme"
Repository = "https://github.com/username/oa-ontology.git"
Issues = "https://github.com/username/oa-ontology/issues"